# Musical constants and mappings for the Money2Music project
import musicpy as mp

# Drum mapping for MIDI drum notes
DRUM_MAPPING = {
    35: 'Acoustic Bass Drum',
    36: 'Bass Drum 1',
    37: 'Side Stick',
    38: 'Acoustic Snare',
    39: 'Hand Clap',
    40: 'Electric Snare',
    41: 'Low Floor Tom',
    42: 'Closed Hi-Hat',
    43: 'High Floor Tom',
    44: 'Pedal Hi-Hat',
    45: 'Low Tom',
    46: 'Open Hi-Hat',
    47: 'Low-Mid Tom',
    48: 'Hi-Mid Tom',
    49: 'Crash Cymbal 1',
    50: 'High Tom',
    51: 'Ride Cymbal 1',
    52: 'Chinese Cymbal',
    53: 'Ride Bell',
    54: 'Tambourine',
    55: 'Splash Cymbal',
    56: 'Cowbell',
    57: 'Crash Cymbal 2',
    58: 'Vibraslap',
    59: 'Ride Cymbal 2',
    60: 'Hi Bongo',
    61: 'Low Bongo',
    62: 'Mute Hi Conga',
    63: 'Open Hi Conga',
    64: 'Low Conga',
    65: 'High Timbale',
    66: 'Low Timbale',
    67: 'High Agogo',
    68: 'Low Agogo',
    69: 'Cabasa',
    70: 'Maracas',
    71: 'Short Whistle',
    72: 'Long Whistle',
    73: 'Short Guiro',
    74: 'Long Guiro',
    75: 'Claves',
    76: 'Hi Wood Block',
    77: 'Low Wood Block',
    78: 'Mute Cuica',
    79: 'Open Cuica',
    80: 'Mute Triangle',
    81: 'Open Triangle'
}   

# Drum categories for easier selection
MAIN_DRUMS = {36, 38, 40, 41, 43, 45, 47, 48, 50}  # Snares, bass, sticks, toms
METAL_DRUMS = {42, 44, 46, 49, 51}  # Hi-hats, crash cymbals

# Get available instruments from musicpy database
try:
    # Get all available instruments from musicpy
    INSTRUMENTS = mp.database.instruments
    # Create a curated list of popular instruments for the UI
    POPULAR_INSTRUMENTS = [
        "Acoustic Grand Piano",
        "Bright Acoustic Piano", 
        "Electric Grand Piano",
        "Honky-tonk Piano",
        "Electric Piano 1",
        "Electric Piano 2",
        "Harpsichord",
        "Clavinet",
        "Celesta",
        "Glockenspiel",
        "Music Box",
        "Vibraphone",
        "Marimba",
        "Xylophone",
        "Tubular Bells",
        "Dulcimer",
        "Drawbar Organ",
        "Percussive Organ",
        "Rock Organ",
        "Church Organ",
        "Reed Organ",
        "Accordion",
        "Harmonica",
        "Tango Accordion",
        "Acoustic Guitar (nylon)",
        "Acoustic Guitar (steel)",
        "Electric Guitar (jazz)",
        "Electric Guitar (clean)",
        "Electric Guitar (muted)",
        "Overdriven Guitar",
        "Distortion Guitar",
        "Guitar Harmonics",
        "Acoustic Bass",
        "Electric Bass (finger)",
        "Electric Bass (pick)",
        "Fretless Bass",
        "Slap Bass 1",
        "Slap Bass 2",
        "Synth Bass 1",
        "Synth Bass 2",
        "Violin",
        "Viola",
        "Cello",
        "Contrabass",
        "Tremolo Strings",
        "Pizzicato Strings",
        "Orchestral Harp",
        "Timpani",
        "String Ensemble 1",
        "String Ensemble 2",
        "SynthStrings 1",
        "SynthStrings 2",
        "Choir Aahs",
        "Voice Oohs",
        "Synth Voice",
        "Orchestra Hit",
        "Trumpet",
        "Trombone",
        "Tuba",
        "Muted Trumpet",
        "French Horn",
        "Brass Section",
        "SynthBrass 1",
        "SynthBrass 2",
        "Soprano Sax",
        "Alto Sax",
        "Tenor Sax",
        "Baritone Sax",
        "Oboe",
        "English Horn",
        "Bassoon",
        "Clarinet",
        "Piccolo",
        "Flute",
        "Recorder",
        "Pan Flute",
        "Blown Bottle",
        "Shakuhachi",
        "Whistle",
        "Ocarina",
        "Lead 1 (square)",
        "Lead 2 (sawtooth)",
        "Lead 3 (calliope)",
        "Lead 4 (chiff)",
        "Lead 5 (charang)",
        "Lead 6 (voice)",
        "Lead 7 (fifths)",
        "Lead 8 (bass + lead)",
        "Pad 1 (new age)",
        "Pad 2 (warm)",
        "Pad 3 (polysynth)",
        "Pad 4 (choir)",
        "Pad 5 (bowed)",
        "Pad 6 (metallic)",
        "Pad 7 (halo)",
        "Pad 8 (sweep)",
        "FX 1 (rain)",
        "FX 2 (soundtrack)",
        "FX 3 (crystal)",
        "FX 4 (atmosphere)",
        "FX 5 (brightness)",
        "FX 6 (goblins)",
        "FX 7 (echoes)",
        "FX 8 (sci-fi)",
        "Sitar",
        "Banjo",
        "Shamisen",
        "Koto",
        "Kalimba",
        "Bagpipe",
        "Fiddle",
        "Shanai",
        "Tinkle Bell",
        "Agogo",
        "Steel Drums",
        "Woodblock",
        "Taiko Drum",
        "Melodic Tom",
        "Synth Drum",
        "Reverse Cymbal",
        "Guitar Fret Noise",
        "Breath Noise",
        "Seashore",
        "Bird Tweet",
        "Telephone Ring",
        "Helicopter",
        "Applause",
        "Gunshot"
    ]
except:
    # Fallback if musicpy database is not available
    POPULAR_INSTRUMENTS = [
        "Acoustic Grand Piano",
        "Electric Piano 1", 
        "Acoustic Guitar (nylon)",
        "Electric Guitar (clean)",
        "Acoustic Bass",
        "Electric Bass (finger)",
        "Violin",
        "Trumpet",
        "Alto Sax",
        "Flute",
        "Lead 1 (square)",
        "Pad 2 (warm)",
        "Synth Bass 1"
    ]

# Rhythm patterns for different musical styles
RHYTHM_VARIANTS = [
    {
        'name': 'Quarter',
        'rhythm': 'b b b b',
        'bars': 1,
        'time_signature': '4/4',
    },
    {
        'name': 'Eighth',
        'rhythm': 'b b b b b b b b',
        'bars': 1,
        'time_signature': '4/4',
    }, 
    {
        'name': 'Tresillo',
        'rhythm': 'b - - b - - b b',
        'bars': 1,
        'time_signature': '4/4',
    },
    {
        'name': 'Double Tresillo',
        'rhythm': 'b 0 0 b 0 0 b 0 0 b 0 0 b 0 b 0',
        'bars': 2,
        'time_signature': '4/4',
    },
    {
        'name': 'Gallop',
        'rhythm': 'b 0 b b b 0 b b',
        'bars': 1,
        'time_signature': '4/4',
    },
    {
        'name': 'Habanera',
        'rhythm': 'b 0 0 b b 0 b 0',
        'bars': 1,
        'time_signature': '4/4',
    },
    {
        'name': 'Barbara Ann',
        'rhythm': 'b 0 b 0 b 0 0 b 0 b 0 b b 0 b 0',
        'bars': 2,
        'time_signature': '4/4',
    },
    {
        'name': 'Aksak 9/8',
        'rhythm': 'b 0 b 0 b 0 b 0 0',
        'bars': 1,
        'time_signature': '9/8',
    },
    {
        'name': 'Son Clave',
        'rhythm': 'b 0 0 b 0 0 b 0 0 0 b 0 b 0 0 0',
        'bars': 2,
        'time_signature': '4/4',
    },
    {
        'name': 'Bossa Nova',
        'rhythm': 'b 0 0 b 0 0 b 0 0 0 b 0 0 b 0 0',
        'bars': 2,
        'time_signature': '4/4',
    },
    {
        'name': 'Mission Impossible 5/4',
        'rhythm': 'b 0 0 b 0 0 b 0 b 0',
        'bars': 1,
        'time_signature': '5/4',
    },
    {
        'name': 'Football Clap',
        'rhythm': 'b 0 b 0 b b b 0 b b b b 0 b b 0',
        'bars': 2,
        'time_signature': '4/4',
    },
]

# Chord pattern variations
PATTERN_VARIANTS = [
    {
        'name': 'Triad',
        'pattern': [1, 2, 3, 1.1, 1, 2, 3, 1.1],
        'intervals': [1/8] * 8,
    }, 
    {
        'name': 'pattern1',
        'pattern': [1.0, 2.0, 3.0, 1.1, 2.0, 3.0, 1.1, 2.0, 3.0, 1.1, 2.0, 3.0, 1.1, 2.0, 3.0, 1.1],
        'intervals': [0.125, 0.0625, 0.0625, 0.0625, 0.0625, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
    },
    {
        'name': 'pattern3',
        'pattern': [1, 1, 3, 2, 3, 2, 1, 4],
        'intervals': [0.125, 0.125, 0.1875, 0.0625, 0.125, 0.125, 0.125, 0.25],
    },
    {
        'name': 'pattern4',
        "intervals": [0.0, 0.125, 0.0, 0.125, 0.125, 0.0, 0.125, 0.0, 0.125, 0.0, 0.125, 0.125, 0.0, 0.125],
        "pattern": [1.0, 1.1, 1.1, 3.0, 1.0, 3.0, 1.1, 4.1, 4.0, 4.0, 3.0, 4.0, 4.0, 3.0],
    }, 
    {
        'name': 'pattern5',
        "intervals": [0.0,0.125,0.0,0.125,0.125,0.0,0.125,0.125,0.0,0.125,0.125,0.0,0.125],
        "pattern": [1.0,1.1,3.1,1.2,1.1,1.2,3.1,1.1,1.2,3.1,1.1,3.1,1.2],
    }
]




